version: "3"

services:
  db-postgres-evento:
    image: postgres:alpine
    ports:
      - "5438:5432"
    container_name: "db-postgres-evento"
    restart: always
    volumes:
      - ./database-postgres-apiPI:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

volumes:
  db-postgres-evento: